label: Identifier
status: ready
context:
  lang: en
  domain:
  masthead:
    label:
      content:
        en: Agency identifier
        es: Identificador de la agencia
    description:
      label:
        content:
          en: Agency description
          es: Descripción de la agencia
    text:
      content:
        en: An official website of the
        es: Un sitio web oficial de
    parent:
      name:
        en: the State of New Jersey
        es: <Parent agency>
      shortname: <Parent shortname>
      url:
        en: https://nj.gov
        es: javascript:void(0);
      logo: default
    agency:
      name:
        en:
        es:
      shortname:
      url:
        en:
        es:
      logo:
    taxpayer_disclaimer:
      content:
        en: Produced and published at taxpayer expense.
        es: Producido y publicado con dinero de los contribuyentes de impuestos.
      display: false
  required_links:
    label:
      content:
        en: Important links
        es: Enlaces importantes
    links:
      about:
        content:
          en: About
          es: Acerca de
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      accessibility:
        content:
          en: Accessibility support
          es: Soporte de accesibilidad
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      foia:
        content:
          en: FOIA requests
          es: Solicitud a través de FOIA
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      no_fear:
        content:
          en: No FEAR Act data
          es: Datos de la ley No FEAR
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      oig:
        content:
          en: Office of the Inspector General
          es: Oficina del Inspector General
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      performance:
        content:
          en: Performance reports
          es: Informes de desempeño
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      privacy:
        content:
          en: Privacy policy
          es: Política de privacidad
        url:
          en: javascript:void(0);
          es: javascript:void(0);
  usagov:
    label:
      content:
        en: U.S. government information and services
        es: Información y servicios del Gobierno de EE. UU.
    description:
      content:
        en: Copyright © 2020 State of New Jersey
        es: ¿Necesita información y servicios del Gobierno?
    display: true

variants:
  - name: lang-es
    label: Spanish
    context:
      lang: es
  - name: no-logos
    label: No Logos
    context:
      masthead:
        parent:
          logo: false
  - name: no-logos-lang-es
    label: No Logos (Spanish)
    context:
      lang: es
      masthead:
        parent:
          logo: false
  - name: multiple-logos
    label: Multiple Logos
    context:
      masthead:
        agency:
          name:
            en: <Other agency>
          shortname: false
          url:
            en: javascript:void(0);
          logo: default
  - name: multiple-logos-lang-es
    label: Multiple Logos (Spanish)
    context:
      lang: es
      masthead:
        agency:
          name:
            es: <Other agency>
          shortname: false
          url:
            es: javascript:void(0);
          logo: default
  - name: taxpayer-disclaimer
    label: Taxpayer disclaimer
    context:
      masthead:
        taxpayer_disclaimer:
          display: true
  - name: taxpayer-disclaimer-lang-es
    label: Taxpayer disclaimer (Spanish)
    context:
      lang: es
      masthead:
        taxpayer_disclaimer:
          display: true
