name: Dependency Check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  npm-audit:
    name: Critical vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # change this back to use the nvmrc file after node is upgraded
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (fail on critical)
        run: npm audit --audit-level=critical

  slack:
    name: Notify Slack on failure
    needs: npm-audit
    if: ${{ needs.npm-audit.result == 'failure' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    uses: newjersey/innovation-shared-actions/.github/workflows/slack.yml@main
    with:
      channel_id: C09Q36G9HMX # sandbox (will update later)
      message: >
        Critial vulnerability detected in ${{ github.repository }} -
        <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View failed workflow run>
    secrets: inherit
